import fs   from 'fs/promises';
import path  from 'path';
import { query }  from '../db/pool.js';
import { eslApi } from '../services/eslService.js';
import { config } from '../config/index.js';

// ─────────────────────────────────────────────────────────────────────────────
// Generates a complete callcenter.conf.xml from the current DB state.
// FreeSWITCH reads this on startup (mod_callcenter), so writing it makes
// queue/agent config survive FS restarts even without the backend running.
// ─────────────────────────────────────────────────────────────────────────────

export async function generateCallcenterXml() {
  const [
    { rows: queues },
    { rows: agents },
    { rows: tiers  },
  ] = await Promise.all([
    query(`SELECT name, strategy, moh_sound, max_wait_time, max_wait_time_w_no_agent, max_queue_size
           FROM queues WHERE active = true ORDER BY name`),
    query(`SELECT agent_id, contact, wrap_up_time, max_no_answer,
                  reject_delay_time, busy_delay_time
           FROM agents WHERE active = true ORDER BY agent_id`),
    query(`SELECT a.agent_id, q.name AS queue_name, t.level, t.position
           FROM agent_tiers t
           JOIN agents a ON a.id = t.agent_id
           JOIN queues q ON q.id = t.queue_id
           WHERE a.active = true AND q.active = true`),
  ]);

  // Group tiers by queue
  const tiersByQueue = {};
  for (const t of tiers) {
    (tiersByQueue[t.queue_name] = tiersByQueue[t.queue_name] || []).push(t);
  }

  const queueXml = queues.map(q => {
    const tierLines = (tiersByQueue[q.name] || [])
      .map(t => `      <tier agent="${t.agent_id}" queue="${q.name}" level="${t.level}" position="${t.position}"/>`)
      .join('\n');

    return `    <queue name="${q.name}">
      <param name="strategy"                          value="${q.strategy}"/>
      <param name="moh-sound"                         value="${q.moh_sound || 'local_stream://moh'}"/>
      <param name="max-wait-time"                     value="${q.max_wait_time}"/>
      <param name="max-wait-time-with-no-agent"       value="${q.max_wait_time_w_no_agent || 0}"/>
      <param name="max-wait-time-with-no-agent-time-reached" value="5"/>
      <param name="max-queue-size"                    value="${q.max_queue_size || 50}"/>
      <param name="tier-rules-apply"                  value="false"/>
      <param name="tier-rule-wait-second"             value="300"/>
      <param name="tier-rule-no-agent-no-wait"        value="true"/>
      <param name="agent-no-answer-status"            value="On Break"/>
      <param name="time-base-score"                   value="queue"/>
${tierLines}
    </queue>`;
  }).join('\n');

  const agentXml = agents.map(a =>
    `    <agent name="${a.agent_id}" type="callback" contact="${a.contact}" status="Logged Out"` +
    ` max-no-answer="${a.max_no_answer}" wrap-up-time="${a.wrap_up_time}"` +
    ` reject-delay-time="${a.reject_delay_time}" busy-delay-time="${a.busy_delay_time}"/>`
  ).join('\n');

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by FS-CC backend — do not edit manually -->
<document type="freeswitch/xml">
  <section name="configuration">
    <configuration name="callcenter.conf" description="CallCenter">
      <settings/>
      <queues>
${queueXml}
      </queues>
      <agents>
${agentXml}
      </agents>
    </configuration>
  </section>
</document>
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Write XML to disk + trigger FreeSWITCH reloadxml.
// Returns { written, filePath, xml } — written=false if FS_CONF_PATH not set.
// ─────────────────────────────────────────────────────────────────────────────

export async function writeAndReloadXml() {
  const xml       = await generateCallcenterXml();
  const confPath  = config.fs?.confPath;

  if (!confPath) {
    console.warn('[queueXml] FS_CONF_PATH not set — XML generated but not written to disk');
    return { written: false, xml };
  }

  const filePath = path.join(confPath, 'autoload_configs', 'callcenter.conf.xml');
  await fs.writeFile(filePath, xml, 'utf8');
  console.log(`[queueXml] ✓ wrote ${filePath}`);

  try {
    const result = await eslApi('reloadxml');
    console.log('[queueXml] reloadxml:', result);
  } catch (err) {
    console.warn('[queueXml] reloadxml failed (ESL offline?):', err.message);
  }

  return { written: true, filePath, xml };
}
